### ISSUE TITLE
Change inline style to classes

### ISSUE THREAD

**Issue by jackishere** [jackishere/htmljack#5]
Please change all the inline styles to Classes with english words :+1: 

Example 
ben --> boy
bat --> girl 

etc ...
@ohad505 @oz1234

**Comment by jackishere** [comment]
יש עוד הרבה סטיילים בתוך הקוד - להפוך הכל לclasses

**Comment by oz1234** [comment]
אני לא מצליח לשמור

**Comment by oz1234** [comment]
טיפלתי בהכול
