### ISSUE TITLE
Add Pictures to kids

### ISSUE THREAD

**Issue by jackishere** [jackishere/htmljack#6]
Download 6 Pictures from the internet in sizes of 100*100 pixel and add to kids as photos
@oz1234

**Comment by oz1234** [comment]
איך מוסיפים תמונה לתיקיה?

**Comment by jackishere** [comment]
אני צריך להדריך אותך בטלפון - תתקשר אליי

**Comment by jackishere** [comment]
יש עוד תמונות בדף שנטענות ישירות מהאינטרנט - תוריד אותן ותעדכן כמקומית

**Comment by oz1234** [comment]
אין
